# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nadeen/SIGCOMM/PANAMA/Vivado/my_netfpga/projects/reference_switch_lite/hw/project/reference_switch_lite.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_bram_if_cntlr_0/control_sub_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'control_sub_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nadeen/SIGCOMM/PANAMA/Vivado/my_netfpga/projects/reference_switch_lite/hw/project/reference_switch_lite.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_bram_if_cntlr_0/control_sub_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'control_sub_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/nadeen/SIGCOMM/PANAMA/Vivado/my_netfpga/projects/reference_switch_lite/hw/project/reference_switch_lite.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_bram_if_cntlr_0/control_sub_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'control_sub_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nadeen/SIGCOMM/PANAMA/Vivado/my_netfpga/projects/reference_switch_lite/hw/project/reference_switch_lite.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_bram_if_cntlr_0/control_sub_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'control_sub_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
