# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nadeen/Vivado/proj/iSLIP_test/test/test.cache/wt [current_project]
set_property parent.project_path /home/nadeen/Vivado/proj/iSLIP_test/test/test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/nadeen/Vivado/proj/iSLIP_test/test/test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/nadeen/Vivado/proj/iSLIP_test/test/test.srcs/sources_1/ip/fifo/fifo.dcp
set_property used_in_implementation false [get_files /home/nadeen/Vivado/proj/iSLIP_test/test/test.srcs/sources_1/ip/fifo/fifo.dcp]
read_verilog -library xil_defaultlib -sv {
  /home/nadeen/Vivado/proj/iSLIP_test/mux.sv
  /home/nadeen/Vivado/proj/iSLIP_test/arbiter.v
  /home/nadeen/Vivado/proj/iSLIP_test/voq.sv
  /home/nadeen/Vivado/proj/iSLIP_test/scheduler.sv
  /home/nadeen/Vivado/proj/iSLIP_test/fabric.sv
  /home/nadeen/Vivado/proj/iSLIP_test/wrapper.sv
}
read_verilog -library xil_defaultlib {
  /home/nadeen/Vivado/proj/iSLIP_test/thermal_dec.v
  /home/nadeen/Vivado/proj/iSLIP_test/p_trans.v
  /home/nadeen/Vivado/proj/iSLIP_test/pp_enc.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top wrapper -part xc7vx690tffg1761-3


write_checkpoint -force -noxdef wrapper.dcp

catch { report_utilization -file wrapper_utilization_synth.rpt -pb wrapper_utilization_synth.pb }
